
/*
 * Auto generated Run-Time-Environment Component Configuration File
 *      *** Do not modify ! ***
 *
 * Project: 'web_pot' 
 * Target:  'XMC4500-F100x1024' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

#define RTE_CMSIS_RTOS                  /* CMSIS-RTOS */
        #define RTE_CMSIS_RTOS_RTX              /* CMSIS-RTOS Keil RTX */
#define RTE_DEVICE
#define RTE_DEVICE_STARTUP
#define RTE_DEVICE_XMCLIB_CAN
#define RTE_DEVICE_XMCLIB_CCU4
#define RTE_DEVICE_XMCLIB_CCU8
#define RTE_DEVICE_XMCLIB_DAC
#define RTE_DEVICE_XMCLIB_DMA
#define RTE_DEVICE_XMCLIB_EBU
#define RTE_DEVICE_XMCLIB_ERU
#define RTE_DEVICE_XMCLIB_FCE
#define RTE_DEVICE_XMCLIB_FLASH
#define RTE_DEVICE_XMCLIB_GPIO
#define RTE_DEVICE_XMCLIB_HRPWM
#define RTE_DEVICE_XMCLIB_I2C
#define RTE_DEVICE_XMCLIB_LEDTS
#define RTE_DEVICE_XMCLIB_POSIF
#define RTE_DEVICE_XMCLIB_RTC
#define RTE_DEVICE_XMCLIB_SCU
#define RTE_DEVICE_XMCLIB_SDMMC
#define RTE_DEVICE_XMCLIB_SPI
#define RTE_DEVICE_XMCLIB_UART
#define RTE_DEVICE_XMCLIB_USB
#define RTE_DEVICE_XMCLIB_VADC
#define RTE_DEVICE_XMCLIB_WDT

#endif /* RTE_COMPONENTS_H */
