/*------------------------------------------------------------------------------
 * uVision/ARM development tools
 * Copyright (C) 2014 ARM Ltd and ARM Germany GmbH. All rights reserved.
 *------------------------------------------------------------------------------
 * Name:    web.c
 * Purpose: ROM Image generated from user specified files.
 * Note:    Generated by FCARM FILE CONVERTER V2.52, do not modify!
 *----------------------------------------------------------------------------*/

#include <stddef.h>
#include <stdint.h>

/* File information */
typedef struct _imageFileItem {
  uint32_t       id;            /* Name identifier (CRC32 value of file name) */
  const uint8_t *data;          /* Data start address in ROM                  */
} imageFileItem;

#define IMAGE_FILE_COUNT 1

/* Last-Modified: Thu, 14 May 2015 17:17:15 GMT */
const uint32_t imageLastModified = 1431623835;

static const uint8_t imageFileData[3] = {

/*-- File: loc.cgx, 3 bytes --*/
0x02,0x4C,0x00,
};

static const imageFileItem imageFileTable[1+1] = {
  { 0x65C757F1, &imageFileData[0] },
  { 0x00000000, &imageFileData[3] }
};

/*
 * Calculate 32-bit CRC (Polynom: 0x04C11DB7)
 *   Parameters:
 *     crc32:       CRC initial value
 *     val:         Input value
 *   Return value:  Calculated CRC value
 */
static uint32_t crc32_8bit (uint32_t crc32, uint8_t val) {
  uint32_t n;

  crc32 ^= ((uint32_t)val) << 24;
  for (n = 8; n; n--) {
    if (crc32 & 0x80000000) {
      crc32 <<= 1;
      crc32  ^= 0x04C11DB7;
    } else {
      crc32 <<= 1;
    }
  }
  return (crc32);
}

/*
 * Get file information from ROM image
 *   Parameters:
 *     name:        File name
 *     data:        Pointer where file data pointer will be written
 *   Return value:  File size
 */
uint32_t imageFileInfo (const char *name, const uint8_t **data) {
  uint32_t id, n;

  if ((name == NULL) || (data == NULL)) return 0;

  id = 0xFFFFFFFF;
  for (; *name; name++) {
    id = crc32_8bit(id, *name);
  }

  for (n = 0; n < IMAGE_FILE_COUNT; n++) {
    if (imageFileTable[n].id == id) {
      *data = imageFileTable[n].data;
      return (imageFileTable[n+1].data - imageFileTable[n].data);
    }
  }
  return 0;
}
